version: '3.9'

services:
  web:
    build: ./backend
    command: daphne -b 0.0.0.0 -p 8000 backend.asgi:application
    volumes:
      - ./backend:/app
      - ./documentos:/documentos           # <-- carpeta de PDFs/KYC disponible en el backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      POSTGRES_HOST: db
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mxm
      REDIS_URL: redis://redis:6379/0
      DJANGO_SETTINGS_MODULE: backend.settings
      PYTHONUNBUFFERED: "1"
    depends_on:
      - db
      - redis
    restart: unless-stopped

  db:
    image: postgres:17
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mxm
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    restart: unless-stopped

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - web
    volumes:
      - ./documentos:/documentos           # <-- misma carpeta montada en el Nginx del frontend
    restart: unless-stopped

volumes:
  postgres_data:
