# Generated by Django 5.2.3 on 2025-07-22 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PrvUsuario",
            fields=[
                (
                    "usuario",
                    models.CharField(max_length=150, primary_key=True, serialize=False),
                ),
                ("clave", models.CharField(max_length=128)),
            ],
            options={
                "db_table": "prv_usuarios",
                "managed": False,
            },
        ),
    ]
